'use client';

import { FormEvent, useEffect, useState } from 'react';
import { insforge } from '../lib/insforge';
import { apiFetch, CurrentUser, InventoryItem, Location, Movement, Page, Product } from '../lib/api';
import { MovementsPanel } from './components/MovementsPanel';
import { Warehouse3D } from './components/Warehouse3D';

type Summary = { products: number; locations: number; occupiedLocations: number; availableLocations: number; totalUnits: number; entriesToday: number; issuesToday: number };
type Tab = 'dashboard' | 'products' | 'locations' | 'inventory' | 'movements' | 'warehouse3d';
const tabs: { id: Tab; label: string }[] = [
  { id: 'dashboard', label: 'Dashboard' }, { id: 'products', label: 'Productos' }, { id: 'locations', label: 'Ubicaciones' }, { id: 'inventory', label: 'Inventario' }, { id: 'movements', label: 'Movimientos' }, { id: 'warehouse3d', label: 'Vista 3D' },
];

export default function HomePage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [user, setUser] = useState<{ email?: string } | null>(null); const [profile, setProfile] = useState<CurrentUser | null>(null); const [token, setToken] = useState<string | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [tab, setTab] = useState<Tab>('dashboard'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => {
    let active = true;
    void (async () => {
      const { data, error: userError } = await insforge.auth.getCurrentUser();
      if (!active) return;
      if (userError || !data?.user) { setLoading(false); return; }
      const { data: session, error: refreshError } = await insforge.auth.refreshSession();
      if (!active) return;
      if (refreshError || !session?.accessToken) { setUser(null); setLoading(false); return; }
      insforge.setAccessToken(session.accessToken);
      setToken(session.accessToken); setUser({ email: data.user.email }); setLoading(false);
    })();
    const unsubscribe = insforge.auth.onAuthStateChange(() => { if (active) setLoading(false); });
    return () => { active = false; unsubscribe(); };
  }, []);
  useEffect(() => { if (!token) return; void Promise.all([apiFetch<Summary>('/dashboard/summary', token), apiFetch<CurrentUser>('/auth/me', token)]).then(([nextSummary, nextProfile]) => { setSummary(nextSummary); setProfile(nextProfile); }).catch((e: Error) => setError(e.message)); }, [token]);
  async function signIn(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const { data, error: authError } = await insforge.auth.signInWithPassword({ email, password }); if (authError || !data?.user || !data.accessToken) { setError(authError?.message ?? 'No fue posible iniciar sesión'); return; } insforge.setAccessToken(data.accessToken); setToken(data.accessToken); setUser({ email: data.user.email }); }
  async function signOut() { await insforge.auth.signOut(); insforge.setAccessToken(null); setToken(null); setUser(null); setProfile(null); setSummary(null); }
  if (loading) return <main className="grid min-h-screen place-items-center">Cargando…</main>;
  if (!user || !token) return <main className="grid min-h-screen place-items-center p-6"><form onSubmit={signIn} className="w-full max-w-md space-y-5 rounded-2xl bg-white p-8 shadow-sm"><p className="text-sm font-semibold uppercase tracking-widest text-brand">WMS</p><h1 className="text-3xl font-bold">Iniciar sesión</h1><label className="block text-sm font-medium">Correo<input className="mt-2 w-full rounded-lg border p-3" type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><label className="block text-sm font-medium">Contraseña<input className="mt-2 w-full rounded-lg border p-3" type="password" required value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-danger">{error}</p>}<button className="w-full rounded-lg bg-brand p-3 font-semibold text-white">Entrar</button></form></main>;
  return <main className="min-h-screen lg:flex"><aside className="bg-[#1E3A8A] p-6 text-white lg:min-h-screen lg:w-64"><p className="text-sm font-semibold uppercase tracking-widest">WMS</p><p className="mt-2 text-xs text-blue-200">Operaciones de bodega</p><nav className="mt-10 space-y-2">{tabs.map(item => <button key={item.id} onClick={() => setTab(item.id)} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${tab === item.id ? 'bg-white/15 font-semibold' : 'text-blue-100 hover:bg-white/10'}`}>{item.label}</button>)}</nav></aside><section className="flex-1 p-6 lg:p-10"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-gray-500">Panel operacional · {profile?.role ?? 'cargando rol'}</p><h1 className="text-3xl font-bold">{tabs.find(item => item.id === tab)?.label}</h1></div><button onClick={signOut} className="rounded-lg border bg-white px-4 py-2 text-sm">{user.email ?? 'Cerrar sesión'}</button></header>{error && <p className="mt-6 rounded-lg bg-red-50 p-3 text-sm text-danger">{error}</p>}<div className="mt-8">{tab === 'dashboard' && <Dashboard summary={summary} />}{tab === 'products' && <Products token={token} role={profile?.role} onError={setError} />}{tab === 'locations' && <Locations token={token} onError={setError} />}{tab === 'inventory' && <Inventory token={token} onError={setError} />}{tab === 'movements' && <MovementsPanel token={token} role={profile?.role} onError={setError} />}{tab === 'warehouse3d' && <Warehouse3D token={token} onError={setError} />}</div></section></main>;
}

function Dashboard({ summary }: { summary: Summary | null }) { const cards = summary ? [['Productos', summary.products], ['Ubicaciones', summary.locations], ['Stock total', summary.totalUnits], ['Ocupadas', summary.occupiedLocations], ['Disponibles', summary.availableLocations], ['Entradas hoy', summary.entriesToday], ['Salidas hoy', summary.issuesToday]] : []; return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <article key={label} className="rounded-xl bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</div>{!summary && <p className="mt-8 text-gray-500">Cargando indicadores…</p>}</>; }

function Products({ token, role, onError }: { token: string; role?: CurrentUser['role']; onError: (value: string) => void }) { const [data, setData] = useState<Page<Product> | null>(null); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [form, setForm] = useState({ sku: '', name: '', unit: 'unidad' }); const canManage = role === 'ADMIN' || role === 'SUPERVISOR'; const load = () => apiFetch<Page<Product>>(`/products?search=${encodeURIComponent(search)}&page=${page}&pageSize=20`, token).then(setData).catch((e: Error) => onError(e.message)); useEffect(() => { void load(); }, [page]); async function submit(e: FormEvent) { e.preventDefault(); try { await apiFetch('/products', token, { method: 'POST', body: JSON.stringify(form) }); setForm({ sku: '', name: '', unit: 'unidad' }); await load(); } catch (e) { onError((e as Error).message); } } return <section className="space-y-5">{canManage ? <form onSubmit={submit} className="grid gap-3 rounded-xl bg-white p-5 shadow-sm md:grid-cols-4"><input required placeholder="SKU" className="rounded-lg border p-3" value={form.sku} onChange={e => setForm({ ...form, sku: e.target.value })} /><input required placeholder="Nombre" className="rounded-lg border p-3" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /><input required placeholder="Unidad" className="rounded-lg border p-3" value={form.unit} onChange={e => setForm({ ...form, unit: e.target.value })} /><button className="rounded-lg bg-brand px-4 py-3 font-semibold text-white">Crear producto</button></form> : <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Tu rol puede consultar productos, pero no crear ni modificar registros.</p>}<div className="rounded-xl bg-white p-5 shadow-sm"><div className="mb-4 flex gap-2"><input placeholder="Buscar por SKU o nombre" className="w-full rounded-lg border p-3" value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === 'Enter' && (setPage(1), void load())} /><button onClick={() => { setPage(1); void load(); }} className="rounded-lg border px-4">Buscar</button></div><Table headers={['SKU', 'Nombre', 'Unidad', 'Estado']} rows={(data?.items ?? []).map(item => [item.sku, item.name, item.unit, item.active ? 'Activo' : 'Inactivo'])} /><Pager page={page} pageSize={data?.pageSize ?? 20} total={data?.total ?? 0} onChange={setPage} /></div></section>; }

function Locations({ token, onError }: { token: string; onError: (value: string) => void }) { const [data, setData] = useState<Page<Location> | null>(null); useEffect(() => { void apiFetch<Page<Location>>('/locations?pageSize=100', token).then(setData).catch((e: Error) => onError(e.message)); }, [token]); return <div className="rounded-xl bg-white p-5 shadow-sm"><Table headers={['Código', 'Nivel', 'Posición', 'Estado']} rows={(data?.items ?? []).map(item => [item.code, item.level, item.position, item.status])} /></div>; }

function Inventory({ token, onError }: { token: string; onError: (value: string) => void }) { const [data, setData] = useState<Page<InventoryItem> | null>(null); useEffect(() => { void apiFetch<Page<InventoryItem>>('/inventory?pageSize=100', token).then(setData).catch((e: Error) => onError(e.message)); }, [token]); return <div className="rounded-xl bg-white p-5 shadow-sm"><Table headers={['SKU', 'Producto', 'Ubicación', 'Cantidad', 'Reservado']} rows={(data?.items ?? []).map(item => [item.product.sku, item.product.name, item.location.code, item.quantity, item.reservedQuantity])} /></div>; }

function Movements({ token, onError }: { token: string; onError: (value: string) => void }) { const [data, setData] = useState<Page<Movement> | null>(null); const [form, setForm] = useState({ productId: '', locationId: '', quantity: 1 }); const load = () => apiFetch<Page<Movement>>('/movements?pageSize=100', token).then(setData).catch((e: Error) => onError(e.message)); useEffect(() => { void load(); }, [token]); async function action(path: string) { try { await apiFetch(path, token, { method: 'POST', body: JSON.stringify(form) }); await load(); } catch (e) { onError((e as Error).message); } } return <section className="space-y-5"><div className="rounded-xl bg-white p-5 shadow-sm"><p className="mb-3 font-semibold">Entrada / salida rápida</p><div className="grid gap-3 md:grid-cols-4"><input placeholder="ID producto" className="rounded-lg border p-3" value={form.productId} onChange={e => setForm({ ...form, productId: e.target.value })} /><input placeholder="ID ubicación" className="rounded-lg border p-3" value={form.locationId} onChange={e => setForm({ ...form, locationId: e.target.value })} /><input type="number" min="1" className="rounded-lg border p-3" value={form.quantity} onChange={e => setForm({ ...form, quantity: Number(e.target.value) })} /><div className="flex gap-2"><button onClick={() => void action('/movements/entry')} className="rounded-lg bg-brand px-3 py-2 text-sm font-semibold text-white">Entrada</button><button onClick={() => void action('/movements/exit')} className="rounded-lg bg-danger px-3 py-2 text-sm font-semibold text-white">Salida</button></div></div></div><div className="rounded-xl bg-white p-5 shadow-sm"><Table headers={['Tipo', 'Producto', 'Cantidad', 'Origen', 'Destino', 'Fecha']} rows={(data?.items ?? []).map(item => [item.type, item.product?.sku ?? '-', item.quantity, item.sourceLocation?.code ?? '-', item.destinationLocation?.code ?? '-', new Date(item.createdAt).toLocaleString()])} /></div></section>; }

function Table({ headers, rows }: { headers: (string | number)[]; rows: (string | number)[][] }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-gray-500">{headers.map(header => <th key={header} className="px-3 py-3">{header}</th>)}</tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={headers.length} className="px-3 py-8 text-center text-gray-500">Sin registros</td></tr> : rows.map((row, index) => <tr key={index} className="border-b last:border-0">{row.map((cell, cellIndex) => <td key={cellIndex} className="px-3 py-3">{cell}</td>)}</tr>)}</tbody></table></div>; }

function Pager({ page, pageSize, total, onChange }: { page: number; pageSize: number; total: number; onChange: (page: number) => void }) { const pages = Math.max(1, Math.ceil(total / pageSize)); return <div className="mt-4 flex items-center justify-between text-sm text-gray-500"><span>Página {page} de {pages} · {total} registros</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => onChange(page - 1)} className="rounded border px-3 py-1 disabled:opacity-40">Anterior</button><button disabled={page >= pages} onClick={() => onChange(page + 1)} className="rounded border px-3 py-1 disabled:opacity-40">Siguiente</button></div></div>; }
